import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parent.parent))

from src.zendesk_client import add_comment_to_ticket


response = add_comment_to_ticket(
ticket_id=2,
    comment="""
Hello,

This response was generated by Resolve AI Agent.

To reset your password:

1. Click Forgot Password.
2. Enter your email.
3. Check your inbox.
4. Follow the reset link.

Regards,
Resolve AI
"""
)

print(response)